version: "2.1"

services:
  env-config:
    image: arribada/env-config
    environment:
      PROMETHEUS_CONFIG: |-
        global:
            scrape_interval:     1s
            evaluation_interval: 1s
    volumes:
    - configs:/configs/
    command:
        - --dir=/configs/
  
  prometheus:
    image: prom/prometheus
    depends_on:
      - env-config
    volumes:
    - configs:/configs/
    ports:
      - 9090:9090
    command:
      - --config.file=/configs/PROMETHEUS_CONFIG
volumes:
  configs:
