orbs:
  docker: arribada/docker@0.0.4
version: 2.1
jobs:
  docker_publish:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout  
      - publish docker/publish:
          containerName:env-config
          
workflows:
  version: 2
  publish:
    jobs:
      - docker_publish:
          filters:
            branches:
                only: 
                  - master
            #   ignore: /.*/
            # tags:
            #   only: /v\d+\.\d+\.\d+$/
