version: 2.1

orbs:
  docker: arribada/docker@0.0.7

workflows:
  version: 2
  publish:
    jobs:
      executor: arribada/ubuntu
      docker/publish:
        containerName: env-config
        context: org-context
        filters:
          branches:
              only: 
                - master
            #   ignore: /.*/
            # tags:
            #   only: /v\d+\.\d+\.\d+$/
